__tests__/index.js
eslintrc.json
package.json

Updates ESLint rules for 2.0.0 compat per the [migration guide](http://eslint.org/docs/user-guide/migrating-to-2.0.0)
• Switches from `space-after-keywords` deprecated rule to `keyword-spacing` rule
• Moves the `quotes` rule to correct position for alphabetical order of rules
• Adds `homepage` and `bugs` recommended fields to `package.json`

ESLint 2.0.0

---

.travis.yml

Node.js v5 will continue to be supported for the next two months in order to give developers currently using v5 time to transition to Node.js v6. - https://nodejs.org/en/blog/release/v6.0.0/

CI: Use the latest NodeJS on Travis CI

---

__tests__/index.js
eslintrc.json
package.json

I _think_ this would be released as a _minor_ semver update, i.e. `5.1.0`:
• Adding `jest` as an additional environment variable should not cause CI failures

feat: Add `jest` as an ESLint environment and switch tests from tape to jest

---

eslintrc.json

Ref: #17 
ESLint rule docs: Notes: http://eslint.org/docs/rules/array-bracket-spacing
The `array-bracket-spacing` is _fixable_ using `--fix` on the [command line](http://eslint.org/docs/user-guide/command-line-interface#fix).

Switch `array-bracket-spacing` to use `never` option

---

eslintrc.json

There are lot's of escaped double quotes within a string in stylelint's codebase. For example, [at-rule-name-space-after's tests](https://github.com/stylelint/stylelint/blob/master/lib/rules/at-rule-name-space-after/__tests__/index.js). This addition will allow us to have less cluttered strings.
```js
// Before
"@charset \"UTF-8\";"
// After
`@charset "UTF-8";`
```
It shouldn't break a build, because both of variants above are accepted.
[Reference](http://eslint.org/docs/rules/quotes#allowtemplateliterals).

Allow template literals for quotes

---

eslintrc.json

https://github.com/stylelint/eslint-config-stylelint/issues/22
`"max-len": [ 2, 120 ]` throws 169 errors on stylelint v8 branch, but with additional options there are only 29 errors.

Add `max-len` rule

---

eslintrc.json
package.json

This prepares the config for use with prettier. It removes the stylistic rules, while keeping the additional error checking and best practise that we’ve added on top of `eslint:recommended`.
Additionally, I’ve added a plugin to ensure `require()`s are alphabetically ordered as this helps with quickly parsing what utils etc a rule is using. The rule can be auto fixed, so rolling it out across the code base will be a breeze.

Prepare for prettier

---

eslintrc.json

https://eslint.org/docs/rules/one-var
We use one `let`, `const` per assignment in our code. [Sometimes](https://github.com/stylelint/stylelint/blob/c7c964f9c5cd503b61a385d2b175445498136bf1/lib/rules/value-no-vendor-prefix/index.js#L50-L52) this rule is broken.

Add one-var rule

---

eslintrc.json
package.json

Hi, stylelint team!
This pull request adds [`eslint-plugin-jest`](https://github.com/jest-community/eslint-plugin-jest) to improve our DX.
- Fixes stylelint/stylelint#3647.
- Enable the [`recommended configuration`](https://github.com/jest-community/eslint-plugin-jest/blob/v21.22.0/index.js#L29).
This change produces so many warnings for our code base. The following rules:
- [`jest/prefer-to-have-length`](https://github.com/jest-community/eslint-plugin-jest/blob/v21.22.0/docs/rules/prefer-to-have-length.md)
- This rule supports auto-fixing, so easy to fix.
- In the recommended configuration, this rule is `warn`. So we may not need to fix it.
- [`jest/no-identical-title`](https://github.com/jest-community/eslint-plugin-jest/blob/v21.22.0/docs/rules/no-identical-title.md)
- This rule points …

Add eslint-plugin-jest

---

eslintrc.json

Follow-up to #53, via https://github.com/stylelint/stylelint/pull/3689#issuecomment-424256507.
Changes violations of `jest/no-identical-title` and `jest/prefer-to-have-length` to be marked as errors instead of warnings. This is part of the recommended config for `jest/no-identical-title` so I removed the local override.

Switch eslint-plugin-jest rules from warn to error

---

eslintrc.js
package.json

Added [`jest/valid-expect-in-promise`](https://github.com/jest-community/eslint-plugin-jest/blob/master/docs/rules/valid-expect-in-promise.md) to avoid error in a test like this one: https://github.com/stylelint/stylelint/pull/3731
The rest functions just to keep tests tidy.

Add more Jest rules

---

eslintrc.js
package.json

`eslint-plugin-eslint-comments` provides rules to apply best practices on ESLint directive comments.
For example, it detects:
- Unused disable comments
- Useless enable comments
- Abuse disable comments (e.g. `/* eslint-disable */` at the beginning of file)
See also:
- https://github.com/mysticatea/eslint-plugin-eslint-comments
- https://mysticatea.github.io/eslint-plugin-eslint-comments

Add eslint-plugin-eslint-comments

---

CHANGELOG.md
eslintrc.js

The `no-console` rule was removed from ESLint v6
> https://eslint.org/docs/user-guide/migrating-to-6.0.0
Adding it back into the config here for:
> https://github.com/stylelint/stylelint/pull/4196

Add `no-console` rule

---

eslintrc.js

Personally, I don't see much benefit in enforcing using `const` whenever possible. In my experience, it have never saved me from a bug, but annoyed a lot, when I had to change from/to `let`.
Here's an Dan Abramov's [article about `prefer-const`](https://overreacted.io/on-let-vs-const/), pros and cons.
This discussion could be heated. So to avoid wasting our time trying to convince on another, lets allow everyone state their position **once**. And then we can vote. Put 👍under this comment for accepting, and 👎for declining change. Only @stylelint members votes would be counted.
We're _not_ going to merge if we have more downvotes, even if this PR would be approved with review system.

Remove `prefer-const`

---

eslintrc.js
package.json

Part of standardisation stream of work.
Closes https://github.com/stylelint/eslint-config-stylelint/issues/69
There are duplicated rules configured in the [`stylelint/stylelint/package.json`](https://github.com/stylelint/stylelint/blob/643289bac28d854009e3eb2da99f388ae3d06975/package.json#L151-L215) and a few additional rules:
```
"eslintConfig": {
"parserOptions": {
"ecmaVersion": 2019
},
"extends": [
"stylelint"
],
"globals": {
"testRule": true
},
"rules": {
"array-callback-return": "error",
"dot-notation": "error",
"func-name-matching": "error",
"guard-for-in": "error",
"no-confusing-arrow": [
"error",
{
"allowParens": false
}
],
"no-else-return": [
"error",
{
"allowElseIf": …
```

Align with configuration in main repo

---

.eslintrc.js

This enables the [`no-shadow`](https://eslint.org/docs/rules/no-shadow) rule.
See <https://github.com/stylelint/stylelint/issues/4985> for the reasons.
Related to https://github.com/stylelint/stylelint/issues/4985 and https://github.com/stylelint/stylelint/pull/4986

Add `no-shadow` rule

---

.github/workflows/nodejs.yml

Node.js 14 [goes LTS on 2020-10-27](https://nodejs.org/en/about/releases/).
See also <https://github.com/stylelint/stylelint/pull/4976>
None.

Add Node.js 14 to CI

---

.eslintrc.js

Given (`foo.js`):
```js
"use strict";
console.log("");
console.warn("");
console.error("");
```
Before:
```
foo.js:3:1: Unexpected console statement. [Error/no-console]
foo.js:4:1: Unexpected console statement. [Error/no-console]
foo.js:5:1: Unexpected console statement. [Error/no-console]
```
After:
```
foo.js:3:1: Unexpected console statement. [Error/no-console]
```
Close #108

Add `allow` option to `no-console`

---

.eslintrc.js
package.json

Updates to align with stylelint v14: https://github.com/stylelint/stylelint/issues/5205
The explicit version ranges have been dropped. `node/no-unsupported-features` is smart enough to pull this from the node engine field of the host project for the version range. Now the two won't fall out of alignment!
I've checked this by linking and fiddling about with the engine field of another project (see attached screen recording, in which I've removes comments to disable checks around fs/promises).
https://user-images.githubusercontent.com/824753/118365313-0f374600-b594-11eb-9c76-1b281d7e93a1.mov

Update node version ranges to align with stylelint v14

---

.eslintrc.js
__tests__/index.test.js
index.js
package-lock.json
package.json

Related to stylelint/stylelint#5291
We are moving to ESM on the `stylelint/stylelint` repo: stylelint/stylelint#5291
This update will be required for the migration.
- Replace [`eslint-plugin-sort-requires`](https://github.com/kentor/eslint-plugin-sort-requires) with the core rule [`sort-imports`](https://eslint.org/docs/rules/sort-imports)
- This change may cause many importing changes...
- Keep this package CommonJS still because ESLint does not seem to support ESM (see eslint/rfcs#9)
I think some changes may be controversial. Please give me feedback!

Update configuration for ESM

---

.github/workflows/nodejs.yml

None.
- Drop Node 10 from the matrix.
- Already End-of-Life. See <https://github.com/nodejs/Release#end-of-life-releases>
- Add Node 16 to the matrix.
- Bump actions/setup-node from v1 to v2
- Set `cache: npm` for speed-up
- See <https://github.com/actions/setup-node#usage>
- Remove useless OS matrix
- Use LTS for Lint removing matrix

Update CI configuration

---

.eslintrc.js
package-lock.json
package.json

Close #141
This change is created by:
- the `npm i eslint-plugin-regexp` command
- a few additions to the `.eslintrc.js` file.
See also https://www.npmjs.com/package/eslint-plugin-regexp

Add eslint-plugin-regexp

---

CHANGELOG.md
package-lock.json
package.json

None.
https://github.com/stylelint/eslint-config-stylelint/compare/13.1.1...HEAD

Prepare 14.0.0

---

.github/workflows/nodejs.yml

Ref: https://github.com/stylelint/eslint-config-stylelint/pull/190#pullrequestreview-1095516960
We usually run linting only for Node.js LTS on CI:
https://github.com/stylelint/.github/blob/7288d228eb3e2ad6bdf9b80afb0b28d502756b35/.github/workflows/lint.yml#L9

Test only for Node.js LTS on CI

---

.eslintrc.js

Ref: https://github.com/stylelint/stylelint/issues/6311
(Stylelint 15.0.0 will drop the support for Node.js 12.)
Node.js 14.5.0 covers more than 90% of the ES2020 features. See [node.green/#ES2020](https://node.green/#ES2020):

Update `parserOptions.ecmaVersion` from `2019` to `2020`

---

package-lock.json
package.json

Following the instruction of ESLint:
> You should declare your dependency on ESLint in `package.json` using the `peerDependencies` field.
See https://eslint.org/docs/latest/extend/shareable-configs#publishing-a-shareable-config

Add `eslint` to `peerDependencies`

---

.editorconfig
.eslintrc.js
README.md
__tests__/helper.js
__tests__/jest.test.js
index.js
jest.js
package-lock.json
package.json

Closes #205
This change extracts the config for Jest from the default one. **Breaking change.**
See the update `README.md` for details.
1. Check out 2 repos:
```
./
├── eslint-config-stylelint/   (on `jest-config` branch)
└── stylelint/                 (on `main` branch)
```
2. Run the commands below:
```console
$ cd eslint-config-stylelint/
$ npm pack
$ cd ../stylelint
$ npm i -D ../eslint-config-stylelint/eslint-config-stylelint-17.1.0.tgz eslint-plugin-jest
$ npm pkg set 'eslintConfig.extends[]=stylelint/jest'
$ npm run lint:js
```
Successful if no lint errors are reported.

[Breaking] Add config for Jest

---

index.js
package-lock.json
package.json

None.
`eslint-plugin-n` is forked from `eslint-plugin-node` which seems no longer maintained,
and is released by the ESLint Community organization.
See https://github.com/eslint-community/eslint-plugin-n
```console
$ npm i -D 'github:stylelint/eslint-config-stylelint#pull/214/merge'
...
$ npm --silent run lint:js
/Users/masafumi.koba/git/stylelint/stylelint/lib/__tests__/fixtures/config-require-unknown.js
3:26  error  "./someUnknownFile.js" is not found                          n/no-missing-require
3:51  error  Definition for rule 'node/no-missing-require' was not found  node/no-missing-require
/Users/masafumi.koba/git/stylelint/stylelint/lib/cli.js
359:3  error  Don't use …
```

Migrate `eslint-plugin-node` to `eslint-plugin-n`

---

index.js

Follow-up to #220
`eslint-plugin-n@16.0.0` defaults to `ecmaVersion: 2021`, see:
https://github.com/eslint-community/eslint-plugin-n/releases/tag/16.0.0

Change `parserOptions.ecmaVersion` from `2020` to `2021`

---

CHANGELOG.md
package-lock.json
package.json

Ref: #222
This change adds `engines.node` to `package.json` to pass `npm run release` (`np`).
If `engines.node` is missing, `np` fails:
```
Error: Please include a `engines.node` field in your package.json
```
Note that we could release `19.0.0` if this PR would approved.
Because `eslint-plugin-n` requires the version. See the following test using [`ls-engines`](https://www.npmjs.com/package/ls-engines):
```console
$ npx ls-engines
`node_modules` found; loading tree from disk...
┌────────┬─────────────────────────────────────────────────────────────────┐
│ engine │ Currently available latest release of each valid major version: │ …
```

Remove Node.js 14 support

---

CHANGELOG.md
index.js

Ref https://github.com/stylelint/stylelint/issues/5291
This change suggests adding the following rules for ESM files.
- [no-restricted-globals](https://eslint.org/docs/latest/rules/no-restricted-globals)
- Disallow the use of CJS global objects.
- [strict](https://eslint.org/docs/latest/rules/strict)
- Disallow the `'use strict'` directive.
Someone may disagree with using `overrides` in sharable configs. Please let me know if you have concerns.
---
I want to automatically check ESM files during the migration from CJS to ESM in the [stylelint/stylelint](https://github.com/stylelint/stylelint) repository.
Also, I believe these enabled rules are useful for other projects.

Add rules for ESM files

---

CHANGELOG.md
index.js

See https://github.com/stylelint/stylelint/pull/7139
Global variables are often harmful. Unlike global variables defined in standard specs (ECMAScript or WHATWG etc.),
`process` is unique to Node.js. This may be a problem when running Stylelint on other platforms.
See https://github.com/eslint-community/eslint-plugin-n/blob/v11.1.0/docs/rules/prefer-global/process.md

Add `n/prefer-global/process` rule

---

CHANGELOG.md
package-lock.json
package.json

None.
Node.js 16 reaches End-of-Life.

Remove Node.js 16 support

---

CHANGELOG.md
index.js

Ref #246
This package supports Node.js 18 or later, which is over 90% compatible with ECMAScript 2023.
See also https://node.green/#ES2023

Change `parserOptions.ecmaVersion` from `2021` to `2023`

---

.eslintrc.js
__tests__/index.test.js
__tests__/jest.test.js
package-lock.json
package.json

None.
The Node.js built-in test runner is mature. We can now reduce dependencies.
Ref https://nodejs.org/api/test.html#test-runner

Migrate Jest to `node:test`/`assert`

---

.github/dependabot.yml

Closes #260
ESLint dependencies are important, so we should update them separately.

Exclude ESLint deps from Dependabot group updates

---

.github/workflows/nodejs.yml

None.
Dependabot always creates a PR when pushing commits, so specifying the branches is unnecessary.

Remove needless Dependabot branches from CI

---

CHANGELOG.md
__tests__/index.test.js
index.js
package-lock.json
package.json

Closes #277
Ref:
- https://eslint.style/rules/default/padding-line-between-statements
- https://eslint.style/packages/js#stylistic-eslint-plugin-js

Replace deprecated `padding-line-between-statements` with `@stylistic/js/padding-line-between-statements`

---

CHANGELOG.md
index.js

None.
First, this rule was deprecated in ESLint v8.53.0. The alternative is the third-party plugin `@stylistic/eslint-plugin-js`.
Second, I sometimes feel annoyed by this rule. For example, see:
```js
const result = () => (type === 'foo' ? foo() : bar());
/*             ^^ Arrow function used ambiguously with a conditional expression [no-confusing-arrow] */
```
In this case, I think it's readable enough, thanks to `()` around the function body.
So, I think this rule is no longer necessary for this shared config.
Ref:
- https://eslint.org/docs/latest/rules/no-confusing-arrow
- https://eslint.org/blog/2023/10/deprecating-formatting-rules
- https://eslint.style/packages/js
> [!NOTE] …

Remove `no-confusing-arrow` because of the deprecation of formatting rules

---

index.js

None.
The `flat/recommended` (`recommended`) config of `eslint-plugin-n` considers both CommonJS and ES modules. I believe this is more flexible for our Stylelint repositories.
Ref <https://github.com/eslint-community/eslint-plugin-n/blob/v17.17.0/README.md#-configs>

Change `eslint-plugin-n` config from `flag/recommended-script` to `flag/recommended` for CJS and ESM

---

__tests__/jest.test.js
package-lock.json
package.json

None.
Unless a dependency is in `dependencies` or `devDependencies`, Dependabot doesn't bump it.
This allows Dependabot to create a pull request to bump `eslint-plugin-jest`.
Note: this won't impact on users because `peerDependencies` doesn't change.
https://github.com/jest-community/eslint-plugin-jest/releases/tag/v28.11.0 was released in January 2025 (about 3 months ago).

Add `eslint-plugin-jest` to `devDependencies` and bump it to 28.11.0

---

.github/dependabot.yml

None.
"development-dependencies" seems a bit too long in a PR title. Shorter titles with "dev-deps" are more readable and still clear. 
E.g.,
```diff
-Bump prettier from 3.5.3 to 3.6.0 in the development-dependencies group
+Bump prettier from 3.5.3 to 3.6.0 in the dev-deps group
```

Shorten dependency group name by Dependabot
