stylelint/eslint-config-stylelint

eslintrc.json
I would like ESLint to stop me from inadvertently leaving console logs when I commit.
=> Add no-console rule

CHANGELOG.md, eslintrc.json
See https://github.com/stylelint/stylelint/pull/1783
=> Add `no-multi-spaces` rule

eslintrc.json
=> Add `padded-blocks` blocks rule with `never` option

eslintrc.json
Suggested in https://github.com/stylelint/stylelint/pull/2262#discussion_r96867449
http://eslint.org/docs/rules/eqeqeq
=> Enforce `===` and `!==`

package.json
=> chore(package): update jest to version 20.0.1

.travis.yml
See https://github.com/stylelint/stylelint/pull/2645
=> Drop Node.js 7.x branch from Travis CI

eslintrc.json, package-lock.json, package.json
Ref https://github.com/stylelint/stylelint/pull/2978
=> Add ESLint `eslint-plugin-node` plugin

.travis.yml, package.json
Related to failing tests in https://github.com/stylelint/eslint-config-stylelint/pull/60
Drop Node 6 as it's reached end of life, add Node 12 as it'll become an LTS release later this year.
=> Update Node versions used in CI

package.json
Closes #60
e.g. "Closes #000" or "None, as it's a documentation fix."
e.g. "No, it's self explanatory."
=> fix(package): update eslint-plugin-node to version 9.1.0

.npmrc, .travis.yml, package.json
https://github.com/stylelint/stylelint/pull/4243
Removed Node.js 8 and 12, because from Travis because we use only Node.js 10 in Travis for other repositories.
=> Use np for pulishing

__tests__/index.test.js, eslintrc.js
Fixes #73, fixes #70 
Waiting to address the other open upstream PRs first.
=> Add new rules

eslintrc.js, package.json
refs https://github.com/stylelint/postcss-css-in-js/pull/27#discussion_r403467626
This PR will be changed to use eslint-config-prettier.
=> Use eslint-config-prettier

.github/workflows/nodejs.yml, .gitignore, .npmrc, LICENSE, package-lock.json, package.json
For release as `@stylelint/eslint-config`
=> Prepare package

CHANGELOG.md
=> Prepare changelog for v12.1.0

CHANGELOG.md
Related PRs:
- #99
Diff: https://github.com/stylelint/eslint-config-stylelint/compare/12.1.0...a3b437c2ce94932d15f99fd84c8b18530bc2dcbb
None.
=> Prepare release for v12.2.0

CHANGELOG.md
This reverts #100. This release includes an added rule, so it is breaking.
See also <https://github.com/stylelint/eslint-config-stylelint/pull/100#issuecomment-708293058>
None.
=> Prepare release for v13.0.0 (reverting v12.2.0)

CHANGELOG.md
Related PRs:
- #109
Diff:
https://github.com/stylelint/eslint-config-stylelint/compare/13.0.0...e482c8ce9d556e832401663f0bd2d2462dde3a98
None.
This PR is a preparation for the next release.
After merging this PR, I'll release the version **13.1.0**.
=> Prepare 13.1.0

.github/workflows/nodejs.yml
None.
- Update using actions
- Add Node.js v18
- Simplify the settings a bit
=> Update CI settings

.github/dependabot.yml
None.
- Limit the number of package updates to `1`.
- The Dependabot PRs are often noisy. We can update dependencies together like [stylelint/stylelint-config-recommended](https://github.com/stylelint/stylelint-config-recommended).
- Add GitHub Actions updates.
=> Update Dependabot settings

CHANGELOG.md
None.
See https://github.com/stylelint/eslint-config-stylelint/compare/15.1.0...HEAD
=> Prepare 16.0.0

.eslintrc.js
Ref: stylelint/stylelint#6377
See https://eslint.org/docs/latest/rules/func-names
=> Add `func-names` rule

package-lock.json, package.json
Ref: https://github.com/stylelint/.github/pull/12
- Add `npm run format` via Prettier
- Run Prettier via `npm run lint`
- Add `npm run pretest` for lint
=> Make npm scripts consistent across our repos

.editorconfig, .eslintrc.js, .github/dependabot.yml, .github/workflows/nodejs.yml, __tests__/index.test.js, index.js, package-lock.json, package.json
This change is created by the following commands:
```shell
npm i -D @stylelint/prettier-config
npm run format
```
I recommend reviewing the code change [by hiding spaces](https://github.com/stylelint/eslint-config-stylelint/pull/208/files?w=1).
=> Use `@stylelint/prettier-config`

.github/workflows/nodejs.yml, CHANGELOG.md, package-lock.json, package.json
- Write changelog
- Bump dependencies
- Try a [merge queue](https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/configuring-pull-request-merges/managing-a-merge-queue).
=> Prepare 18.0.0

CHANGELOG.md
None.
Diff: https://github.com/stylelint/eslint-config-stylelint/compare/18.0.0...main
=> Prepare 19.0.0

.github/dependabot.yml
None.
See https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file#groups
=> Enable Dependabot group update for dev deps

.github/workflows/release.yml, package.json
Ref https://github.com/stylelint/stylelint/pull/7112
Ref https://github.com/stylelint/jest-preset-stylelint/pull/70
See https://github.com/stylelint/changelog-to-github-release-action
=> Create release with GitHub Actions

.github/dependabot.yml
None.
We now use group updates, so it's unneeded to worry if the number of Pull Requests is too many.
=> Increase `open-pull-requests-limit` in `dependabot.yml`

CHANGELOG.md
None.
See https://github.com/stylelint/eslint-config-stylelint/compare/21.0.0...c7acf9d
=> Add changelog item for next version

CHANGELOG.md
None.
Shall I release after we merge this?
=> Prepare 23.0.0

CHANGELOG.md
None.
Here are changes since the previous version <https://github.com/stylelint/eslint-config-stylelint/releases/tag/23.0.0>:
https://github.com/stylelint/eslint-config-stylelint/compare/23.0.0...65a68f9
=> Prepare 24.0.0
